services:

  fluxgym:
    build:
      context: .
      # change the dockerfile to Dockerfile.cuda12.4 if you are running CUDA 12.4 drivers otherwise leave as is
      dockerfile: Dockerfile
    image: fluxgym
    container_name: fluxgym
    ports:
      - 7860:7860
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/app/fluxgym
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"          # Use only GPU with index 1
              capabilities: [gpu]
          memory: 32g           # Optional: Reserve 32 GB RAM
        limits:
          memory: 32g           # Max RAM usage
    memswap_limit: 40g          # Total allowed memory+swap (48g RAM + 12g swap)
    restart: unless-stopped
    #shm_size: "8g"